### ISSUE TITLE
Can minify static/styles.css

### ISSUE THREAD

**Issue by reina3596** [Takeno/CI_Assetic#1]
Hello,

Your library is 99% perfect. All functionality its ok but I can not minify the file css in "production".

Its posible to use yui or other for minify?

Thanks

**Comment by Takeno** [comment]
Hi
This feature is available in Assetic library, but I don't implement it yet. If you need it, you can register filters in Assetic as described here:
https://github.com/kriswallsmith/assetic#filters

I'll try to implement this feature soon.

**Comment by omarherri** [comment]
Hi i was using your library for while, so i'm wondering if you get managed to implement minify feature??

**Comment by Takeno** [comment]
Hi @omarname! I'm not working anymore on this library.

You can register yuicompressor or others here: https://github.com/Takeno/CI_Assetic/blob/master/application/libraries/assetic.php#L55 as described here: https://github.com/kriswallsmith/assetic#filters

**Comment by omarherri** [comment]
> Hi @omarname! I'm not working anymore on this library.
> 
> You can register yuicompressor or others here: https://github.com/Takeno/CI_Assetic/blob/master/application/libraries/assetic.php#L55 as described here: https://github.com/kriswallsmith/assetic#filters

Thanks a lot, i'll give it a try.
